--
-- PostgreSQL database dump
--

\restrict UgU5jGM1KeDxl5BJjaih4DRfuVUTsKjXCHYUVzVJ37PQwfCKoZDOyC0S7BVhzAF

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_banner; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_banner (
    id bigint NOT NULL,
    heading character varying(200) NOT NULL,
    subheading character varying(300) NOT NULL,
    tag_label character varying(80) NOT NULL,
    image character varying(100),
    overlay_opacity smallint NOT NULL,
    is_active boolean NOT NULL,
    "order" smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT catalog_banner_order_check CHECK (("order" >= 0)),
    CONSTRAINT catalog_banner_overlay_opacity_check CHECK ((overlay_opacity >= 0))
);


ALTER TABLE public.catalog_banner OWNER TO postgres;

--
-- Name: catalog_banner_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_banner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_banner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_orderitem (
    id bigint NOT NULL,
    weight_kg numeric(8,2) NOT NULL,
    price_per_kg numeric(10,2) NOT NULL,
    line_total numeric(10,2) NOT NULL,
    order_id bigint NOT NULL,
    vegetable_id bigint NOT NULL
);


ALTER TABLE public.catalog_orderitem OWNER TO postgres;

--
-- Name: catalog_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_preorder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_preorder (
    id bigint NOT NULL,
    order_number character varying(50) NOT NULL,
    buyer_name character varying(200) NOT NULL,
    contact_person character varying(200) NOT NULL,
    phone_number character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    pickup_date date NOT NULL,
    pickup_time_slot character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    total_weight_kg numeric(10,2) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    special_instructions text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.catalog_preorder OWNER TO postgres;

--
-- Name: catalog_preorder_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_preorder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_preorder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_vegetable; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_vegetable (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    code character varying(50) NOT NULL,
    price_per_kg numeric(10,2) NOT NULL,
    image character varying(100),
    description text NOT NULL,
    category character varying(50) NOT NULL,
    is_available boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.catalog_vegetable OWNER TO postgres;

--
-- Name: catalog_vegetable_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_vegetable ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_vegetable_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Order Item	7	add_orderitem
26	Can change Order Item	7	change_orderitem
27	Can delete Order Item	7	delete_orderitem
28	Can view Order Item	7	view_orderitem
29	Can add Vegetable	8	add_vegetable
30	Can change Vegetable	8	change_vegetable
31	Can delete Vegetable	8	delete_vegetable
32	Can view Vegetable	8	view_vegetable
33	Can add Pre-Order	9	add_preorder
34	Can change Pre-Order	9	change_preorder
35	Can delete Pre-Order	9	delete_preorder
36	Can view Pre-Order	9	view_preorder
37	Can add Banner	10	add_banner
38	Can change Banner	10	change_banner
39	Can delete Banner	10	delete_banner
40	Can view Banner	10	view_banner
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$870000$SM6d6Y1x5fNf1I5EOBjVFr$V6trAQh28Bc2zw65d909aSI2fhTh+A0o6xGRoQY8krg=	2026-08-31 17:39:53.072964+05:30	t	Rayees-AC			info.rayeesac@gmail.com	t	t	2026-08-31 15:49:42.96115+05:30
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: catalog_banner; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_banner (id, heading, subheading, tag_label, image, overlay_opacity, is_active, "order", created_at) FROM stdin;
1	Fresh Chinese vegetables, pre-ordered by the kilogram	Select your weights, submit a pre-order, and we pack your bulk lot for pickup or delivery. Your invoice is generated the moment you submit.	WHOLESALE PRE-ORDERS	banners/hero-produce-CWKeHrzS.jpg	55	t	0	2026-08-31 17:21:58.208168+05:30
2	Fresh Chinese vegetables, pre-ordered by the kilogram	Select your weights, submit a pre-order, and we pack your bulk lot for pickup or delivery. Your invoice is generated the moment you submit.	WHOLESALE PRE-ORDERS	banners/images.jpg	55	t	0	2026-08-31 18:13:30.726435+05:30
4	Green Produce Border	A lush cluster of green vegetables, zucchini, broccoli, and apples gathered on the left side of a dark moody slate background.	WHOLESALE PRE-ORDERS	banners/images-1.jpg	55	t	0	2026-08-31 18:18:23.863176+05:30
3	Fresh Vegetables & Herbs Flat Lay	A top-down culinary arrangement featuring vibrant red onions, tomatoes, herbs, and chili on a dark textured stone slate.	WHOLESALE PRE-ORDERS	banners/images-3.jpg	55	f	0	2026-08-31 18:18:00.634468+05:30
\.


--
-- Data for Name: catalog_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_orderitem (id, weight_kg, price_per_kg, line_total, order_id, vegetable_id) FROM stdin;
1	1.00	9.00	9.00	1	1
2	0.50	3.00	1.50	1	3
3	1.50	7.00	10.50	1	2
4	0.50	7.00	3.50	2	2
5	1.00	150.00	150.00	3	5
6	0.50	50.00	25.00	3	2
7	0.50	85.00	42.50	3	9
8	1.50	85.00	127.50	4	9
9	0.25	50.00	12.50	4	2
10	0.80	100.00	80.00	4	7
11	0.50	130.00	65.00	4	1
12	0.50	100.00	50.00	5	7
\.


--
-- Data for Name: catalog_preorder; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_preorder (id, order_number, buyer_name, contact_person, phone_number, email, pickup_date, pickup_time_slot, status, total_weight_kg, total_amount, special_instructions, created_at) FROM stdin;
1	LCV-2026-00001	rayees	rayees	7902343487	info.rayeesac@gmail.com	2026-09-01	6	pending	3.00	21.00	aaa	2026-08-31 15:55:42.096745+05:30
2	LCV-2026-00002	www	ww	7902343387	info.rayeesac@gmail.com	2026-10-02	6	pending	0.50	3.50	sssss	2026-08-31 16:00:45.520494+05:30
3	LCV-2026-00003	rayees	rayees	7902343487		2026-08-31	1	completed	2.00	217.50	xx	2026-08-31 17:47:19.153728+05:30
4	LCV-2026-00004	aa	aa	1234567890	info.rayeesac@gmail.com	2026-08-31	1	pending	3.05	285.00	sss	2026-08-31 18:00:11.724271+05:30
5	LCV-2026-00005	ac store	riyas	1234567890		2026-09-02	6	pending	0.50	50.00	note	2026-08-31 20:04:31.145991+05:30
\.


--
-- Data for Name: catalog_vegetable; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_vegetable (id, title, code, price_per_kg, image, description, category, is_available, created_at) FROM stdin;
6	Capsicum	CAPSICUM	120.00	vegetables/Screenshot_From_2026-08-31_17-39-01.png	Capsicum	shoots	t	2026-08-31 17:41:18.823629+05:30
8	Yellow zucchinis	YELLOW ZUCCHINIS	80.00	vegetables/Screenshot_From_2026-08-31_17-38-46_mM9TF7c.png	Yellow zucchinis	other	t	2026-08-31 17:42:49.717512+05:30
9	iceberg lettuce	ICEBERG LETTUCE	85.00	vegetables/Screenshot_From_2026-08-31_17-38-29.png	iceberg lettuce	cabbages	t	2026-08-31 17:43:52.416769+05:30
3	Chinese Cabbage (Wombok)	CHINESE CABBAGE (WOMBOK)	65.00	vegetables/cat-cabbage.jpg	Chinese Cabbage (Wombok)	cabbages	t	2026-08-31 15:54:35.392954+05:30
1	Snow Peas	SNOW_PEAS	130.00	vegetables/cat-pods.jpg	aa	gourds	t	2026-08-31 15:52:50.485709+05:30
2	Coriander	CORIANDER	50.00	vegetables/cat-herbs.jpg	Coriander	leafy_greens	t	2026-08-31 15:54:06.924042+05:30
4	Water Spinach (Kangkung)	WATER SPINACH (KANGKUNG)	75.00	vegetables/cat-leafy-B2FB4f9c.jpg	Water Spinach (Kangkung)	leafy_greens	t	2026-08-31 17:26:26.933109+05:30
5	Strawberry	STRAWBERRY	150.00	vegetables/Screenshot_From_2026-08-31_17-37-57.png	Strawberry	other	t	2026-08-31 17:40:43.90198+05:30
7	Green zucchinis	GREEN ZUCCHINIS	100.00	vegetables/Screenshot_From_2026-08-31_17-38-54.png	Green zucchinis	gourds	t	2026-08-31 17:42:30.915644+05:30
10	Red Russian kal	RED RUSSIAN KAL	35.00	vegetables/Screenshot_From_2026-08-31_18-27-01.png	Red Russian kal	other	t	2026-08-31 18:28:15.864525+05:30
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-08-31 15:52:50.486465+05:30	1	Snow Peas (snow_peas)	1	[{"added": {}}]	8	1
2	2026-08-31 15:54:06.924558+05:30	2	Coriander (Coriander)	1	[{"added": {}}]	8	1
3	2026-08-31 15:54:35.39402+05:30	3	Chinese Cabbage (Wombok) (Chinese Cabbage (Wombok))	1	[{"added": {}}]	8	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	catalog	orderitem
8	catalog	vegetable
9	catalog	preorder
10	catalog	banner
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-31 15:49:20.633786+05:30
2	auth	0001_initial	2026-08-31 15:49:20.656716+05:30
3	admin	0001_initial	2026-08-31 15:49:20.669312+05:30
4	admin	0002_logentry_remove_auto_add	2026-08-31 15:49:20.676278+05:30
5	admin	0003_logentry_add_action_flag_choices	2026-08-31 15:49:20.682822+05:30
6	contenttypes	0002_remove_content_type_name	2026-08-31 15:49:20.691871+05:30
7	auth	0002_alter_permission_name_max_length	2026-08-31 15:49:20.697733+05:30
8	auth	0003_alter_user_email_max_length	2026-08-31 15:49:20.703788+05:30
9	auth	0004_alter_user_username_opts	2026-08-31 15:49:20.707686+05:30
10	auth	0005_alter_user_last_login_null	2026-08-31 15:49:20.713697+05:30
11	auth	0006_require_contenttypes_0002	2026-08-31 15:49:20.715315+05:30
12	auth	0007_alter_validators_add_error_messages	2026-08-31 15:49:20.721554+05:30
13	auth	0008_alter_user_username_max_length	2026-08-31 15:49:20.727379+05:30
14	auth	0009_alter_user_last_name_max_length	2026-08-31 15:49:20.73163+05:30
15	auth	0010_alter_group_name_max_length	2026-08-31 15:49:20.73776+05:30
16	auth	0011_update_proxy_permissions	2026-08-31 15:49:20.741362+05:30
17	auth	0012_alter_user_first_name_max_length	2026-08-31 15:49:20.745752+05:30
18	sessions	0001_initial	2026-08-31 15:49:20.749745+05:30
19	catalog	0001_initial	2026-08-31 15:50:24.985239+05:30
20	catalog	0002_banner	2026-08-31 17:19:44.088324+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
qwtspfy6bb80jv9pr1v0hs34ck6x8w0t	.eJxVjMsOwiAQAP9lz4ZQaGHbo3e_geyyIFUDSR8n47-bJj3odWYybwi0byXsa1rCLDBBB5dfxhSfqR5CHlTvTcVWt2VmdSTqtKu6NUmv69n-DQqtBSbobbYaJUdkLUYTsaWRcXAsJovH5CwbSqLZObQ46NiN1gsmH3vsM8LnC_sGODs:1x0z8i:Nr-OxgsYWSwE27HZOJEQ6AUdx-lISWJ_-b7Plzt96P0	2026-09-14 15:51:20.599909+05:30
00ttm6qdhqlj5m6pb0gikw5mhrsylr7y	.eJxVjMsOwiAQAP9lz4ZQaGHbo3e_geyyIFUDSR8n47-bJj3odWYybwi0byXsa1rCLDBBB5dfxhSfqR5CHlTvTcVWt2VmdSTqtKu6NUmv69n-DQqtBSbobbYaJUdkLUYTsaWRcXAsJovH5CwbSqLZObQ46NiN1gsmH3vsM8LnC_sGODs:1x10pl:nXs7CJyO3g2PKAgkLM81EaHpn4r86NIM_XvdHj59WGU	2026-09-14 17:39:53.076629+05:30
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: catalog_banner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_banner_id_seq', 4, true);


--
-- Name: catalog_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_orderitem_id_seq', 12, true);


--
-- Name: catalog_preorder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_preorder_id_seq', 5, true);


--
-- Name: catalog_vegetable_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_vegetable_id_seq', 10, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 3, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: catalog_banner catalog_banner_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_banner
    ADD CONSTRAINT catalog_banner_pkey PRIMARY KEY (id);


--
-- Name: catalog_orderitem catalog_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_orderitem
    ADD CONSTRAINT catalog_orderitem_pkey PRIMARY KEY (id);


--
-- Name: catalog_preorder catalog_preorder_order_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_preorder
    ADD CONSTRAINT catalog_preorder_order_number_key UNIQUE (order_number);


--
-- Name: catalog_preorder catalog_preorder_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_preorder
    ADD CONSTRAINT catalog_preorder_pkey PRIMARY KEY (id);


--
-- Name: catalog_vegetable catalog_vegetable_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_vegetable
    ADD CONSTRAINT catalog_vegetable_code_key UNIQUE (code);


--
-- Name: catalog_vegetable catalog_vegetable_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_vegetable
    ADD CONSTRAINT catalog_vegetable_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: catalog_orderitem_order_id_14fa89a5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_orderitem_order_id_14fa89a5 ON public.catalog_orderitem USING btree (order_id);


--
-- Name: catalog_orderitem_vegetable_id_437bf7a7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_orderitem_vegetable_id_437bf7a7 ON public.catalog_orderitem USING btree (vegetable_id);


--
-- Name: catalog_preorder_order_number_188379fb_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_preorder_order_number_188379fb_like ON public.catalog_preorder USING btree (order_number varchar_pattern_ops);


--
-- Name: catalog_vegetable_code_2e960830_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_vegetable_code_2e960830_like ON public.catalog_vegetable USING btree (code varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_orderitem catalog_orderitem_order_id_14fa89a5_fk_catalog_preorder_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_orderitem
    ADD CONSTRAINT catalog_orderitem_order_id_14fa89a5_fk_catalog_preorder_id FOREIGN KEY (order_id) REFERENCES public.catalog_preorder(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_orderitem catalog_orderitem_vegetable_id_437bf7a7_fk_catalog_vegetable_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_orderitem
    ADD CONSTRAINT catalog_orderitem_vegetable_id_437bf7a7_fk_catalog_vegetable_id FOREIGN KEY (vegetable_id) REFERENCES public.catalog_vegetable(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict UgU5jGM1KeDxl5BJjaih4DRfuVUTsKjXCHYUVzVJ37PQwfCKoZDOyC0S7BVhzAF

