# Generated by Django 5.1.4 on 2026-08-31 10:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Business / Client Name')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Contact Person')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pickup_date', models.DateField(verbose_name='Preferred Pickup / Delivery Date')),
                ('pickup_time_slot', models.CharField(blank=True, help_text='e.g. 6:00 AM – 9:00 AM', max_length=100, verbose_name='Preferred Time Slot')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Weight (kg)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount ($)')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Packing / Delivery Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pre-Order',
                'verbose_name_plural': 'Pre-Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='SKU / Product Code')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price per kg ($)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vegetables/')),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('leafy_greens', 'Leafy Greens'), ('cabbages', 'Cabbages'), ('herbs', 'Herbs'), ('root_vegetables', 'Root Vegetables'), ('gourds', 'Gourds & Melons'), ('shoots', 'Shoots & Stems'), ('other', 'Other')], default='other', max_length=50)),
                ('is_available', models.BooleanField(default=True, verbose_name='In Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vegetable',
                'verbose_name_plural': 'Vegetables',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Weight (kg)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per kg ($)')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Line Total ($)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.preorder')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.vegetable')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
