# Generated by Django 5.1.4 on 2026-08-31 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Large hero heading text.', max_length=200)),
                ('subheading', models.CharField(blank=True, help_text='Smaller descriptive text beneath the heading.', max_length=300)),
                ('tag_label', models.CharField(blank=True, default='WHOLESALE PRE-ORDERS', help_text='Small uppercase label above the heading (e.g. "WHOLESALE PRE-ORDERS").', max_length=80)),
                ('image', models.ImageField(blank=True, help_text='Background image for the banner. Recommended size: 1600×600 px.', null=True, upload_to='banners/')),
                ('overlay_opacity', models.PositiveSmallIntegerField(default=55, help_text='Background overlay darkness 0–90 (default 55).', validators=[django.core.validators.MaxValueValidator(90)])),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
