# Generated by Django 5.1.4 on 2026-09-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vegetable',
        ),
        migrations.DeleteModel(
            name='PreOrder',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
