# Generated by Django 5.1.4 on 2026-09-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_preorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='price_per_kg',
        ),
    ]
