# Generated by Django 5.1.4 on 2026-09-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_price_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='culinary_uses',
            field=models.TextField(blank=True, help_text='How this vegetable is typically cooked or used.', verbose_name='Culinary Uses'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='health_benefits',
            field=models.TextField(blank=True, help_text='Key health benefits of this vegetable (displayed on the detail page).', verbose_name='Health Benefits'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='nutrients',
            field=models.TextField(blank=True, help_text='Notable nutrients, minerals and dietary fibre content.', verbose_name='Nutrients & Minerals'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='origin',
            field=models.CharField(blank=True, help_text='Where this vegetable originates from.', max_length=200, verbose_name='Origin / Region'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='vitamins',
            field=models.TextField(blank=True, help_text='Vitamins present in significant amounts.', verbose_name='Vitamins'),
        ),
    ]
