# Generated by Django 5.1.4 on 2026-09-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_vegetable_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='details_html',
            field=models.TextField(blank=True, help_text='Full details entered via the rich-text editor on the manage page.', verbose_name='Details (rich text)'),
        ),
    ]
