# Generated by Django 5.1.4 on 2026-09-30 14:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_details_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='details_html',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full details entered via the rich-text editor on the manage page.', verbose_name='Details (rich text)'),
        ),
    ]
